services:
  # Backend Service (Updated)
  backend:
    build: ./backend
    environment:
      - PYTHONPATH=/app
      # Added username (root) and password (password) to the connection string
      - DATABASE_URL=mongodb://root:password@mongo:27017
      
      - DATABASE_NAME=todo_app
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID} # Reads from root .env file
      - SECRET_KEY=${SECRET_KEY}             # Reads from root .env file
    volumes:
      # This volume is now only used for local file storage if needed in the future.
      # Database data is handled by the 'mongo-data' named volume.
      - ./backend-data:/data
    depends_on:
      - mongo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Frontend Service
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy

  # Database Service (Updated)
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    # This will create a root user with the specified credentials on initialization.
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: